// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4c-3KCXbDUxRSdGrohiJs1tzlRBf46a8',
    appId: '1:1029362855198:android:0c4b2e07d817f0f7a62d0f',
    messagingSenderId: '1029362855198',
    projectId: 'kamo-7b1be',
    databaseURL: 'https://kamo-7b1be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kamo-7b1be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCynRle0fo64rikdCdqQPBQgFSZCmf_Wok',
    appId: '1:1029362855198:ios:e09ba02641c6f305a62d0f',
    messagingSenderId: '1029362855198',
    projectId: 'kamo-7b1be',
    databaseURL: 'https://kamo-7b1be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kamo-7b1be.firebasestorage.app',
    androidClientId: '1029362855198-7o07ogqjptuuqbgsjcbhpd4984vq2b19.apps.googleusercontent.com',
    iosClientId: '1029362855198-ac2l5bv1c2sam26567be34s9icto2f67.apps.googleusercontent.com',
    iosBundleId: 'com.kaamo.app',
  );

}